---
name: dist

on:
  pull_request:
  push:
    branches:
    - main
    tags:
    - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SCCACHE_WEBDAV_ENDPOINT: "https://frcmaven.wpi.edu/artifactory/wpilib-generic-cache-cmake-local"
  SCCACHE_WEBDAV_KEY_PREFIX: "sccache-robotpy"

jobs:
  # This job limits concurrency on the default branch
  # - we want it to run so it can populate ccache, but we typically
  #   don't care about when it completes, so limit its concurrency
  #   to stop eating up valuable + slow Windows/macOS runners
  setup_concurrency:
    runs-on: ubuntu-latest
    outputs:
      max-parallel: ${{ steps.max-parallel.outputs.p }}
    steps:
    - name: Setup concurrency
      shell: bash
      id: max-parallel
      run: |
        if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "PARALLEL=1"
          echo "p={\"v\": 1}" >> $GITHUB_OUTPUT
        else
          echo "PARALLEL=10000"
          echo "p={\"v\": 10000}" >> $GITHUB_OUTPUT
        fi

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable

    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install deps
      shell: bash
      run: |
        python -m pip --disable-pip-version-check install -r rdev_requirements.txt

    - name: Check pyproject / rdev synchronization
      shell: bash
      run: |
        ./rdev.sh ci check-pyproject

  build-arm:
    runs-on: ubuntu-22.04-arm
    needs: [setup_concurrency]
    strategy:
      max-parallel: ${{ fromJSON(needs.setup_concurrency.outputs.max-parallel).v }}
      fail-fast: true
      matrix:
        python_version:
        - '3.10'
    container: python:${{ matrix.python_version }}-bullseye

    steps:
    - run: apt-get update && apt-get install -y libgl1

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #
    # Setup build caching
    #

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.7

    # See https://github.com/pypa/setuptools_scm/issues/784
    - name: Set git directory as safe to allow setuptools-scm to work
      shell: bash
      run: |
        /usr/bin/git config --global --add safe.directory $PWD

    - name: Install deps
      shell: bash
      run: |
        python -m pip --disable-pip-version-check install -r rdev_requirements.txt

    - name: Install numpy (needed for stubgen)
      shell: bash
      run: |
        python -m pip --disable-pip-version-check install numpy

    - name: Build + test wheels
      shell: bash
      run: |
        ./rdev.sh ci run
      env:
        RPYBUILD_STRIP_LIBPYTHON: "1"
        RPYBUILD_CC_LAUNCHER: sccache
        SCCACHE_WEBDAV_USERNAME: ${{ secrets.WPI_ARTIFACTORY_USERNAME }}
        SCCACHE_WEBDAV_PASSWORD: ${{ secrets.WPI_ARTIFACTORY_TOKEN }}

    - uses: actions/upload-artifact@v4
      with:
        name: "pypi-${{ runner.os }}-arm-${{ matrix.python_version }}"
        path: dist
